### ISSUE TITLE
Upgrade dependencies?

### ISSUE THREAD

**Issue by james-hu** [ozum/concat-md#17]
I am using concat-md together with typedoc, which is exactly the same way how the documentation in this repo is generated. It his quite useful. Thank you!

NPM complains about some outdated dependencies of concat-md. I can see there are some PRs here not being handled for a long time. 

So just wonder, is this repo still be maintained? Any chance to get dependencies upgraded?

**Comment by ozum** [comment]
Hi.

All possible modules are updated. Some of the modules' new versions require to switch to es modules, which is not backward compatible)
