### ISSUE TITLE
Problem to understand how works --decrease-title-levels

### ISSUE THREAD

**Issue by cavo789** [ozum/concat-md#2]
Hello

I'm probably doing something wrong: I've a folder called `userguide` with one readme.md and one subfolder by chapter. Each folder has his own index.md.

So, I've four .md files

```
└─ doc
   └─ userguide
         ├─ readme.md
         ├─ Chapter 1
         │  ├─ index.md
         ├─ Chapter 2
         │  ├─ index.md
         ├─ Chapter 3
         │  ├─ index.md
   └─ concat.bat
```

In my parent `doc` folde, I've a `concat.bat` script with this command : `concat-md --decrease-title-levels userguide`

So, my understanding was: the four markdown files will be taken and, with respect to the folder's hierarchy, level of title will be decreased (H1 will become H2).

But no, it doesn't work like that.

I get this:

```markdown
<a name="readmemd"></a>
# My amazing doc (readme.md)

<a name="chapter-1indexmd"></a>
# Chapter 1 (chapter1/readme.md)

<a name="chapter-2indexmd"></a>
# Chapter 2 (chapter2/readme.md)
## Chapter 2.1

<a name="chapter-3indexmd"></a>
# Chapter 3 (chapter3/readme.md)
## Chapter 3.1
## Chapter 3.2
```

My expectation was to get  `## Chapter 1` i.e. the H1 in `chapter 1/index.md` becomes a H2.

Does `--decrease-title-levels` shouldn't follow how deep the tree-structure is ?

[Dummy markdown files used](https://github.com/ozum/concat-md/files/3597591/doc.zip)

Thanks!

**Comment by ozum** [comment]
Sorry, I missed this question for a long time because no notification is sent to me. If the issue still persist, please reopen. Thanks.

**Comment by cavo789** [comment]
Hello

No more tried since then because I've code my own set of scripts in Bash to work with md and documentation generation.
